name: General Checks
on:
  pull_request:
    types: [ assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review, review_requested ]
  pull_request_review:
    types: [ submitted, edited, dismissed ]

concurrency:
  group: ci-general-checks-${{ github.ref }}
  cancel-in-progress: true


env:
  CI: true
jobs:
  init:
    name: 'DangerJS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn danger ci -i 'Code-Quality-Check' --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
